# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b9778057e8c3ad1d5a9dc423865c332066a4ced3ffac488b47f323623c8b94e889f27afa01962ea4e45d3e74161328398b942e088bea7c0e228304e466a65f3

test:
  secret_key_base: 73874ea191dbd1448ef58da78129ffcc1477761aa96cc173b394612296f4e9ec0d54f08ebac50a47e1cc80bd6b471878607a9c06f7b09ea668cfff48c4a8969e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
